export const DOXIE_DYNASTY = {
  NAME: 'Doxie Dynasty Card Game',
  ORIGINAL_PRICE: 3499,
  CURRENT_PRICE: 2499,
  MIN_QUANTITY: 1,
  MAX_QUANTITY: 10,
  FREE_SHIPPING: true,
  SHIPPING_DAYS: '5-7',
  RETURN_DAYS: 30,
  MAX_CUSTOMER_NAME_LENGTH: 100,
  MAX_CUSTOMER_EMAIL_LENGTH: 254,
  MAX_GIFT_NOTE_LENGTH: 300,
} as const;
